apiVersion: api.demo.demo.com/v1alpha
kind: Scalar
metadata:
  labels:
    app.kubernetes.io/name: scalerproject
    app.kubernetes.io/managed-by: kustomize
  name: scalar-samples
spec:
  start: 6
  end: 7
  replicas: 3
  deployments: 
    - name: nginx
      namespace: default
